name: country_picker_enterprise
description: Enterprise-grade country picker widget for Flutter with multi-language support, phone codes, smart search functionality, and auto country detection.
version: 1.0.1
homepage: https://github.com/stanislavworldin/flutter_country_picker
repository: https://github.com/stanislavworldin/flutter_country_picker
issue_tracker: https://github.com/stanislavworldin/flutter_country_picker/issues
documentation: https://github.com/stanislavworldin/flutter_country_picker#readme
topics:
  - flags
  - country
  - picker
  - search
  - codes

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

# Platform support
platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # Assets for screenshots in README
  assets:
    - screenshots/

screenshots:
  - description: "Country Picker Interface"
    path: screenshots/screen.png
